version: '3.9'

services:
    postgres:
        image: postgres:14
        container_name: soccer_postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - postgres_data:/var/lib/postgresql/postgres_data
        ports:
            - "5432:5432"
        env_file:
            - .env
    
    
    pgadmin:
        image: dpage/pgadmin4
        container_name: soccer_pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        ports:
            - "5050:80"
        depends_on:
            - postgres
        env_file:
            - .env

volumes:
    postgres_data: {}
